CREATE TABLE Utilisateur (
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Prenom VARCHAR(255) NOT NULL,
    Nom VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    MotDePasse VARCHAR(255) NOT NULL,
    EstAdmin BOOLEAN
);
CREATE TABLE VehiculesOccasion (
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Titre VARCHAR(255) NOT NULL,
    Photo VARCHAR(255) NOT NULL,
    Prix float NOT NULL,
    Km INT(255) NOT NULL,
    Annee INT NOT NULL,
    Description TEXT NOT NULL,
    Modele VARCHAR(255) NOT NULL,
    Marque VARCHAR(255) NOT NULL,
    Statut VARCHAR(255) NOT NULL
);

CREATE TABLE VehiculePhotos (
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    VehiculeId INT NOT NULL, 
    Chemin text NOT NULL
);
CREATE TABLE VehiculeCaracteristiques (
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    VehiculeId INT NOT NULL, 
    Titre VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL
);
CREATE TABLE GarageService (
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Titre VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Photo VARCHAR(255)
);
CREATE TABLE FormulaireDeContact (
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Nom VARCHAR(255) NOT NULL,
    Prenom VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Telephone VARCHAR(15) NOT NULL,
    FormulaireMessage VARCHAR(255) NOT NULL
);
CREATE TABLE AvisClients (
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Nom VARCHAR(255) NOT NULL,
    Prenom VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Commentaire VARCHAR(255) NOT NULL,
    Note INT NOT NULL,
    EstApprouve BOOLEAN NOT NULL
);
CREATE TABLE Horaires (
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Commentaire VARCHAR(255) NOT NULL
);
